# CS559 - F20 Project #1

## Task Desciption
You are provided with an anonymized dataset containing numeric feature variables, the binary target column, and a string ID_code column.

The task is to predict the value of `target` column in the test set using either **Logistic Regression** and **SVM**. You are welcome to use **regularizaiton**. 

## File descriptions
- train.csv - the training set (202 columns)

- test.csv - the test set. The test set contains some rows which are not included in scoring.

## Rules
- The data does not have specific column names. Therefore, you will not know what data is about. 
- However, you still can do classicaition problem without clustering the training set. **No unsupervised learning techniques in this project**. 
- There are 202 columns. This means that the key of high accuracy comes from **EDA** and **feature enegineering**. 
- There are no rules on EDA and Feature Engineering. 
- On your model, make sure you can reduce the columns at the most of 25%. If we use all columns, we may have high computational cost and getting into bias-variance tradeoff and underfit vs. overfit situations. 
- The project is out of 100. 
    - 50 points will come from your EDA and any pre-processing work. 
    - 30 points will come from your model: Accuracy + overcoming any ML challenges. 
    - 10 points will come from in-class competition. 
        - Ranking the accuracy with less features. 
    - 10 points will come from a report describing your work flow and model evaluations.
        - must be submitted in different file (e.g., pdf, docx). 
        
## Recommand Before-Preprocessing
- You can split the set from the data distribution. 
- You can make multiple new data frames by randomly selecting columns. 
- You can do similar by rows. 

## Recommand Before-training model
- Make sure to delete features from supportive reasons. 

Proejct DUE: 10/23/2020 Friday 11:59 PM. 




# Avaneesh Kolluri

**I pledge my honor that I have abided by the Stevens Honor System.**

*I will be making my comments to describe my work flow and model evaluations.*

In [2]:
# Below are the import statements for most of the functions used
import pandas as pd
import numpy as np
from sklearn.linear_model import Lasso
from sklearn.linear_model import LogisticRegression
import sklearn as sk
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import ElasticNet
from sklearn.preprocessing import normalize
from scipy import stats
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [3]:
df = pd.read_csv("train.csv")

In [4]:
x_vals = df.drop(columns = ['target','ID_code'])
y_vals = df['target']

In [5]:
# This was the data for one of the models
kbest_and_corr_features = df.drop(columns = ['target','ID_code'])
kbest_and_corr_features.loc[:,'var_0':'var_199'] = normalize(df.drop(columns = ['target','ID_code']))
y_vals = df['target']

In [6]:
model4Vals = df.drop(columns = ['target','ID_code'])

In [7]:
model5Vals = df.drop(columns = ['target','ID_code'])

In [8]:
model6Vals = df.drop(columns = ['target','ID_code'])

# Feature Extraction for Lasso Regression

*I wanted to use the Select From Model in order to detect which features contribute to predict the target value. I wanted to use regression, and Lasso specifically to select variables and regularize the data. Because this would find vectors that minimize the prediction error, by trying to shrink the coefficients to exactly zero. I split my data into two portions and tested to see if we can remove any features in order to save time, but this test was inconclusive. L1 is Lasso.*

In [9]:
x = normalize(x_vals)
x_vals.loc[:,'var_0':'var_199'] = x
x1 = x_vals.iloc[:,0:(len(x_vals.columns)//2)]
x2 = x_vals.iloc[:,(len(x_vals.columns)//2 +1):]

In [10]:
# Normalizing the data points from 0-1, giving them an equal range for all.
las_scaler = StandardScaler()
las_scaler.fit(x1)
lasso_reg = SelectFromModel(LogisticRegression(penalty = 'l1'))
lasso_reg.fit(las_scaler.transform(x1),y_vals)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


SelectFromModel(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l1', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
        max_features=None, norm_order=1, prefit=False, threshold=None)

In [11]:
# Normalizing the data points from 0-1, giving them an equal range for all.
las_scaler = StandardScaler()
las_scaler.fit(x2)
lasso_reg = SelectFromModel(LogisticRegression(penalty = 'l1'))
lasso_reg.fit(las_scaler.transform(x2),y_vals)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


SelectFromModel(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l1', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
        max_features=None, norm_order=1, prefit=False, threshold=None)

In [12]:
lasso_indexes = []
# This code checks how many features were reported to be removed
for i in range(len(lasso_reg.get_support())):
    if lasso_reg.get_support()[i] == False:
        lasso_indexes.append(i)
lasso_indexes

[]

*This Lasso test was inconclusive as it suggested to keep all 200 features, which obviously is not the best approach when working with Feature Extraction Techniques.*

# Feature Extraction for Ridge Regression

*The Code here is for Ridge Regression. Ridge regression essentially would be checking the data values that are hurting the model due to multicollinearity, meaning their variances would be distant from the actual true value, so I also used Select Best Model in order to find the features it shows to keep and which ones to remove. I wanted to use Select from model over RFE because in RFE you have to pick how many features to keep, while Select From Model will analyze the all the features and give you a boolean array of what to keep or not. It is different from Lasso, because in Ridge, it shrinks the values TOWARDS zero, versus exactly zero. L2 is for Ridge Regression.*

In [13]:
# Need to scale it from 0-1 before running it through the model
ridge_scaler = StandardScaler()
ridge_scaler.fit(x_vals)
ridge_reg = SelectFromModel(LogisticRegression(penalty = 'l2'))
ridge_reg.fit(ridge_scaler.transform(x_vals),y_vals)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


SelectFromModel(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
        max_features=None, norm_order=1, prefit=False, threshold=None)

In [14]:
# Get all the indexes in which the boolean statements were false, so we can remove it
ridge_indexes = []
for i in range(len(ridge_reg.get_support())):
    if ridge_reg.get_support()[i] == False:
        ridge_indexes.append(i)
len(ridge_indexes)

121

In [15]:
# Remove all relvent columns and edit the Data Frame
ridgeDrop = []
for i in ridge_indexes:
    colName = 'var_' + str(i)
    ridgeDrop.append(colName)
filtered_x = x_vals.drop(columns = ridgeDrop)

**Below is Extraction for Model 4**. 
*Model 4 is working on checking which features to use on non-normalized data*

In [16]:
ridgeModel4 = StandardScaler()
ridgeModel4.fit(model4Vals)
ridge_regModel4 = SelectFromModel(LogisticRegression(penalty = 'l2'))
ridge_regModel4.fit(ridgeModel4.transform(model4Vals),y_vals)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


SelectFromModel(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
        max_features=None, norm_order=1, prefit=False, threshold=None)

In [17]:
# This code below saves the indexes in which to remove from the features
# It will return the total number of features needed to remove based on the results
ridge_indexes = []
for i in range(len(ridge_regModel4.get_support())):
    if ridge_regModel4.get_support()[i] == False:
        ridge_indexes.append(i)
len(ridge_indexes)

104

In [18]:
# This iterates through the columns and removes the columns based on the indexes saved and edits the 
# DataFrame
ridgeDrop = []
for i in ridge_indexes:
    colName = 'var_' + str(i)
    ridgeDrop.append(colName)
model4Vals = model4Vals.drop(columns = ridgeDrop)

# Linear Discriminant Analysis

*The bottom code is the code to use Linear Discriminant Analysis in order to see which features can be removed to simplify the data. Linear Discriminant Analysis is primarily used to model differences in groups, thus helping feature extraction products, to reduce the dimensions of the data. By Classifying the features into categories, then usinfg Select Best Model on them, with the boolean array used from get_support, I can find which features to remove from a specific dataset if even necessary.*

In [19]:
lda_scaler = StandardScaler()
lda_scaler.fit(filtered_x)
lda_reg = SelectFromModel(LinearDiscriminantAnalysis())
lda_reg.fit(lda_scaler.transform(filtered_x),y_vals)

SelectFromModel(estimator=LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001),
        max_features=None, norm_order=1, prefit=False, threshold=None)

In [20]:
lda_reg.get_support()

array([False, False, False, False,  True, False,  True, False,  True,
        True,  True, False,  True, False, False, False, False,  True,
       False,  True, False,  True, False,  True,  True, False, False,
       False, False,  True, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False, False, False,  True, False,  True,  True, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False])

In [21]:
lda_indexes = []
for i in range(len(lda_reg.get_support())):
    if lda_reg.get_support()[i] == False:
        lda_indexes.append(i)
len(lda_indexes)

59

In [22]:
headers = list(filtered_x.columns)
len(lda_reg.get_support())

79

In [23]:
ldaDrop = []
headers = list(filtered_x.columns)
for i,j in zip(lda_reg.get_support(), headers):
    if(i == False):
        ldaDrop.append(j)
LDA_Ridge_data = filtered_x.drop(columns = ldaDrop)

In [24]:
# Feature Extraction Below for Model 4

In [25]:
m4_scaler = StandardScaler()
m4_scaler.fit(model4Vals)
m4_reg = SelectFromModel(LinearDiscriminantAnalysis())
m4_reg.fit(m4_scaler.transform(model4Vals),y_vals)

SelectFromModel(estimator=LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001),
        max_features=None, norm_order=1, prefit=False, threshold=None)

In [26]:
m4_reg.get_support()

array([ True,  True,  True, False,  True, False,  True,  True, False,
        True,  True, False, False,  True, False,  True,  True, False,
       False,  True, False,  True, False, False,  True, False,  True,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False,  True, False,  True, False,  True, False, False,
       False,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False,  True, False,  True, False,
       False,  True, False,  True,  True, False, False,  True, False,
       False, False, False, False,  True,  True, False,  True,  True,
       False, False,  True, False,  True, False,  True, False, False,
        True,  True,  True, False, False,  True])

In [27]:
# Making sure the features that the model told me to remove are removed from the dataset
model4Vals = model4Vals[model4Vals.columns[m4_reg.get_support()]]

In [28]:
# Model 4's features are a subset of model 5's so I am just copying the data to a new variable to save time
# and memory.
model5Vals = model4Vals.copy(deep = True)

# Correlations of Features

*Another approach I wanted to takin in terms of feature extraction was to look at the correlation in relation to the actual target value and remove the ones that were least correlated with the target value as they could be helping to overfit the data or they woul not provide any analysis or inference on the data, thus useless.*

*However, my findings were that most of the data points were not really closely correlated with the  target value as most of the points had a correlation value of around .05 to -.05. However I just wanted to see if removing the low correlations had a positive affect on some of my models so for one model I removed a decent amount of features when I removed the ones that had a correlation value of less than .025 and greater than -.025. For mey second model that I removed some features using correlation, my threshhold was .045 to -.045, but even then I was only able to remove 3 features based on already the processed data. However, as it can be seen and explained later I did not end up choosing a model that included this correlation extraction model.*

*Also, in the code, you will see that I do cm[0][1:]. This is  because cm is my correlation matrix, and cm[0] is the correlation of my target value's correlation to everything else, and I sliced from the first index down, as the 0'th index is the target in relation to itself which will always be one, but I only care about the features so I removed that one value.*

In [29]:
corr_df = df.drop(columns = ['ID_code'])
corr_df.loc[:,'var_0':'var_199'] = LDA_Ridge_data
corr_df = corr_df.dropna(axis = 1, how = 'all')

In [30]:
cm=np.corrcoef(corr_df.values.T)

In [31]:
# This shows no variables have a moderate or strong correlation with the target.
remove_i_cols = []
lst = cm[0][1:]
for i in range(len(lst)):
    if lst[i] > -.025 and lst[i] < .025:
        remove_i_cols.append(i)

In [32]:
count = 0
droppedCols = []
for colName,data in LDA_Ridge_data.iteritems():
    if count in remove_i_cols:
        droppedCols.append(colName)
    count += 1
corr25_ldaRidge = LDA_Ridge_data.drop(columns = droppedCols)

In [33]:
# Now Extracting Features for kbest_and_corr_features dataset
corr_df2 = df.drop(columns = ['ID_code'])
corr_df2.loc[:,'var_0':'var_199'] = kbest_and_corr_features
corr_df2 = corr_df2.dropna(axis = 1, how = 'all')
cm=np.corrcoef(corr_df2.values.T)

In [34]:
remove_i_cols = []
lst = cm[0][1:]
for i in range(len(lst)):
    if lst[i] > -.025 and lst[i] < .025:
        remove_i_cols.append(i)
        
dk = []
count = 0
for colName,data in kbest_and_corr_features.iteritems():
    if count in remove_i_cols:
        dk.append(colName)
    count += 1
kbest_and_corr_features = kbest_and_corr_features.drop(columns = dk)

In [35]:
# Extracting for Model 5

In [36]:
corr_df = df.drop(columns = ['ID_code'])
corr_df.loc[:,'var_0':'var_199'] = model5Vals
corr_df = corr_df.dropna(axis = 1, how = 'all')
cm=np.corrcoef(corr_df.values.T)

In [37]:
remove_i_cols = []
lst = cm[0][1:]
for i in range(len(lst)):
    if lst[i] > -.045 and lst[i] < .045:
        remove_i_cols.append(i)

In [38]:
count = 0
droppedCols = []
for colName,data in model5Vals.iteritems():
    if count in remove_i_cols:
        droppedCols.append(colName)
    count += 1
model5Vals = model5Vals.drop(columns = droppedCols)

In [39]:
# Below is the Extraction Code for Model 6

In [40]:
corr_df = df.drop(columns = ['ID_code'])
corr_df.loc[:,'var_0':'var_199'] = model6Vals
corr_df = corr_df.dropna(axis = 1, how = 'all')
cm=np.corrcoef(corr_df.values.T)

In [41]:
remove_i_cols = []
lst = cm[0][1:]
for i in range(len(lst)):
    if lst[i] > -.025 and lst[i] < .025:
        remove_i_cols.append(i)
        
dk = []
count = 0
for colName,data in model6Vals.iteritems():
    if count in remove_i_cols:
        dk.append(colName)
    count += 1
model6Vals = model6Vals.drop(columns = dk)

# Selecting K Best Features

*The next extraction approach I applied to some of my model sets of data was using the K Best Features approach. The K best features gets to choos the first k best features that would help predict your test set. Specifically I ran the model on a chi squared distribution, which wouldessentially look at the dependence value in relation to the target values and remove the fesatures that aren't needed. I had to use a min max scalaer for this becasue negative values can't be used for the chi squared function, so I normalized it to a positive number.*

In [42]:
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import MinMaxScaler

In [43]:
scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(kbest_and_corr_features)
t = scaler.transform(kbest_and_corr_features)

In [44]:
kbestcorr = SelectKBest(chi2, k=50)
kbestcorr.fit_transform(t, y_vals)

array([[0.3975948 , 0.3140128 , 0.53710406, ..., 0.56464541, 0.31793714,
        0.30021665],
       [0.48830424, 0.42425939, 0.60193757, ..., 0.6484659 , 0.47743041,
        0.51616646],
       [0.42435434, 0.45848352, 0.6145575 , ..., 0.527662  , 0.64516098,
        0.46396209],
       ...,
       [0.49828765, 0.3831504 , 0.45381534, ..., 0.55197195, 0.3853606 ,
        0.3417794 ],
       [0.39400409, 0.27341231, 0.56375533, ..., 0.50476595, 0.50564942,
        0.36471573],
       [0.50237656, 0.34945227, 0.56641005, ..., 0.70876746, 0.21125289,
        0.28487645]])

In [45]:
l = kbestcorr.get_support()

In [46]:
keeps = []
for title, b in zip(kbest_and_corr_features.columns,l):
    if b:
        keeps.append(title)
kbest_and_corr_features = kbest_and_corr_features[keeps]

In [47]:
# Below is the Continuation of the Extraction process for Model 6

In [48]:
scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(model6Vals)
t = scaler.transform(model6Vals)

In [49]:
mk6 = SelectKBest(chi2, k=50)
mk6.fit_transform(t, y_vals) # Scaled it so that Non-Negative Values will not Exist

array([[0.42785307, 0.32482435, 0.56805853, ..., 0.56951454, 0.34294267,
        0.32765751],
       [0.55721218, 0.42863943, 0.6812351 , ..., 0.66807851, 0.53653095,
        0.6095461 ],
       [0.41196889, 0.48377668, 0.57806091, ..., 0.52249633, 0.64314053,
        0.42583343],
       ...,
       [0.5432771 , 0.39305749, 0.4870996 , ..., 0.55813267, 0.41905483,
        0.38087342],
       [0.46750324, 0.25309006, 0.66682332, ..., 0.51568196, 0.58482497,
        0.46661746],
       [0.5258457 , 0.36714503, 0.580254  , ..., 0.70933049, 0.22572933,
        0.29469964]])

In [50]:
l = mk6.get_support()

In [51]:
# Based on what the model told me to keep, I am keeping the relavent features.
keeps = []
for title, b in zip(model6Vals.columns,l):
    if b:
        keeps.append(title)
model6Vals = model6Vals[keeps]

# Analyzing the Confusion Matrices

*The code below takes in a 2x2 matrix (a confusion matrix) and will return the true negatives and true positives to help simplify that analyzing porocess of a Confusion Matrix*

In [52]:
def analyze_Confusion(lst):
    negatives = sum(lst[0])
    positives = sum(lst[1])
    tn = lst[0][0]/negatives
    tp = lst[1][1]/positives
    print(f'Model predicted Zeros {tn*100}% correctly.')
    print(f'Model predicted Ones {tp*100}% correctly.')
    return (tn*100, tp*100)

# Training the Model

*The following arrays are to keep track of the scores and accuracy of each parameter to make is visually appealable and comparable afterwards.*

In [113]:
scores = []
ones = []
zeros = []

*Below are the ten models I trained with various test sets with different combinations of features and also different classifiers such as SVM and Logistic Regression. Although in its name "regression," it is a classifier. I have labelled which feature extraction techniquest I used above each model.*

**Using only Ridge and LDA for Logistic AFTER NORMALIZING (Model 1)**

*This is a Logistic Regression Model*

*For this dataset, I first used ridge regression and called select best model on it, which suggested to remove about over 100 features, so I did so. Then the next feature extraction technique that I used was LDA, which I described above. This brough the used features to this model to 20 Features.*

*The model as it can be seen through the Confusion matrix and score was predicting almost 90% correctly. So, it shows that it is not overfitting. Although it is predicting almost all 0's correctly, it is predicting almost all 1's incorrectly, which explains why the accuracy is 90% because about 90% of the values are 0's*

In [53]:
final_model = LogisticRegression(penalty = 'l2').fit(LDA_Ridge_data,y_vals)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [54]:
fval = final_model.predict(LDA_Ridge_data)

In [115]:
sc = final_model.score(LDA_Ridge_data,y_vals)
sc

0.899675

In [116]:
from sklearn.metrics import confusion_matrix
x = confusion_matrix(y_vals, fval)
print(x)
(z, o) = analyze_Confusion(x)
scores.append(sc)
ones.append(o)
zeros.append(z)

[[179886     16]
 [ 20049     49]]
Model predicted Zeros 99.99110626896866% correctly.
Model predicted Ones 0.24380535376654394% correctly.


In [57]:
m1Columns = LDA_Ridge_data.columns

**Using only Ridge, LDA, and Correlation w/ threshold of +-.025 for Logistic AFTER NORMALIZING (Model 2)**

*This is a Logistic Regression Model*

*For this data I used ridge regression, and LDA to remove features up to 20, then I also removed the correlations that were very close to zero even though many were less than .05, so I used .025 to -.025. This one also had an accuracy of 90% about, and as it can be seen through correlation matrix, it was barely predictiong the ones correctly, and most predictions was 0.*

In [58]:
rlc = LogisticRegression(penalty = 'l2').fit(corr25_ldaRidge,y_vals)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [59]:
rlc_prediction = rlc.predict(corr25_ldaRidge)

In [117]:
sc = rlc.score(corr25_ldaRidge,y_vals)
sc

0.899675

In [118]:
# Don't use this model because it is only predicting 2 ones
from sklearn.metrics import confusion_matrix
x = confusion_matrix(y_vals, rlc_prediction)
print(x)
(z, o) = analyze_Confusion(x)
scores.append(sc)
ones.append(o)
zeros.append(z)

[[179886     16]
 [ 20049     49]]
Model predicted Zeros 99.99110626896866% correctly.
Model predicted Ones 0.24380535376654394% correctly.


In [62]:
m2Columns = corr25_ldaRidge.columns 

**Using Correlation and K Best Feature Selector AFTER NORMALIZING (Model 3)**

*This is a Logistic Regression Model*

*For selecting the features for this model, I used the correlation techniques and k best selector as I described the process in the EDA section. For correlation, I removed values that were less than .025 and greater than -.025 as they are super insignificant. Then I selected the 50 best features from k-best. This showed to be a little more accurate due to score, as it was able to predict more ones correctly as well. As it can be seen through the confusion matrix, this model predicted a few more ones properly, which is up to 7%.*

In [63]:
clf_corrkbest = LogisticRegression(penalty = 'l2').fit(kbest_and_corr_features,y_vals)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [64]:
clf_corrkbest_prediction = clf_corrkbest.predict(kbest_and_corr_features)

In [119]:
sc = clf_corrkbest.score(kbest_and_corr_features,y_vals)
sc

0.90413

In [120]:
from sklearn.metrics import confusion_matrix
x = confusion_matrix(y_vals, clf_corrkbest_prediction)
print(x)
(z, o) = analyze_Confusion(x)
scores.append(sc)
ones.append(o)
zeros.append(z)

[[179328    574]
 [ 18600   1498]]
Model predicted Zeros 99.6809373992507% correctly.
Model predicted Ones 7.453477958005772% correctly.


In [67]:
m3Columns = kbest_and_corr_features.columns

**Using only Ridge and LDA for Logistic WITHOUT NORMALIZING (Model 4)**

*This is a Logistic Regression Model*

*For the next 3 models, I did not normalize the data. This was because I was realizing that as I was normalizing the data, the ranges only max out at 1, and because we have a binary target with already less amount of ones, it wasn't able to recognize the 1 values as they may have been outliers, but by not normalizing, the features were able to provide more information in deciding the one values as well.*

*I used the same approach for picking these features as I did for the first model, but the difference was that I did not normalize the data. So, different features were used. It can be seen that now, it was predicting a few more ones correctly rather than predicting all zero's right or wrong.*

In [68]:
model4 = LogisticRegression(penalty = 'l2').fit(model4Vals,y_vals)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [69]:
model4_predictions = model4.predict(model4Vals)

In [121]:
sc = model4.score(model4Vals,y_vals)
sc

0.90508

In [122]:
from sklearn.metrics import confusion_matrix
x = confusion_matrix(y_vals, model4_predictions)
print(x)
(z, o) = analyze_Confusion(x)
scores.append(sc)
ones.append(o)
zeros.append(z)

[[178782   1120]
 [ 17864   2234]]
Model predicted Zeros 99.37743882780626% correctly.
Model predicted Ones 11.115533883968553% correctly.


In [72]:
m4Columns = model4Vals.columns

**Using only Ridge, LDA, and Correlation w/ threshold of +-.045 for Logistic WITHOUT NORMALIZING (Model 5)**

*This is a Logistic Regression Model*

*As explained previously, I did not want to use normalized data to see the difference, so I used the same approach as I did for the second model, except now using non-normalized data, and also a higher correlation threshhold to remove more features. This score was 90%, but was predicting a less amount of ones overall in comparision to the previous model. However, still performs better than the models that did use normalization techniques.*

In [73]:
model5 = LogisticRegression(penalty = 'l2').fit(model5Vals,y_vals)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [74]:
model5_predictions = model5.predict(model5Vals)

In [123]:
sc = model5.score(model5Vals,y_vals)
sc

0.90447

In [124]:
from sklearn.metrics import confusion_matrix
x = confusion_matrix(y_vals, model5_predictions)
print(x)
(z, o) = analyze_Confusion(x)
scores.append(sc)
ones.append(o)
zeros.append(z)

[[178843   1059]
 [ 18047   2051]]
Model predicted Zeros 99.41134617736324% correctly.
Model predicted Ones 10.204995521942482% correctly.


In [77]:
m5Columns = model5Vals.columns

**Using Correlation and K Best Feature Selector WITHOUT NORMALIZING (Model 6)**

*This is a Logistic Regression Model*

*For the same reasons explained above, I wanted to try theis model without normaliing the data. I used the same approach of feature extraction as the third model, but the only difference was that I was using non-normalized data. This was the model that predicted the number of 1's the most for Logistic regressions, but I did not want to use the model if it extracted using correlation unless it was **significantly** better than another model. The reason for this is because all of the features have significantly low correlations, removing some that are close to 0 isn't that good of a strategy as all the points are far less than .1, so a correlation of .03 wouldn't help much more than a correlation of .02, which is why I wanted to use another model that had more of a mathematical reason to extract features. This also wasnt much more effective in predicting the 1's correctly, so I felt like the model just got lucky.*

In [78]:
model6 = LogisticRegression(penalty = 'l2').fit(model6Vals,y_vals)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [79]:
model6_predictions = model6.predict(model6Vals)

In [125]:
sc = model6.score(model6Vals,y_vals)
sc

0.906095

In [126]:
from sklearn.metrics import confusion_matrix
x = confusion_matrix(y_vals, model6_predictions)
print(x)
(z, o) = analyze_Confusion(x)
scores.append(sc)
ones.append(o)
zeros.append(z)

[[178585   1317]
 [ 17464   2634]]
Model predicted Zeros 99.26793476448289% correctly.
Model predicted Ones 13.105781669817892% correctly.


In [82]:
m6Columns = model6Vals.columns

**SVM Classifier Using only Ridge and LDA for Logistic AFTER NORMALIZING (Model 7)**

*The next 4 models are Support Vector Machine Models (SVM). SVM is a linear classifier that essentially classifies the points based on the the plane the point lies on in order to classify it as a specific class. I had to run a sample of the train data for 20% of the data as the computational time was extremely long and too much for my computer to process at a stretch.*

*I am using the same features extracted using the model 1 feature extraction process, with normalized sata. Essentially, the data being inputted into this model is the same as that of model one's. The score is 90%, but as I was looking deeper, it is 90% because it did not predict a single one, and predicted all zero's for the set of data, which is why the score is decieving , but there are 90% 0's in the data, which is why the score is decieving. This was one of the worst models, as well as took too much computational time, which is why I had to run the model on a random sample of 20% of the data, but the results were the same with 20% of the data or 100% of the data.*

In [128]:
svmCLF = SVC(gamma='auto')

In [129]:
svm1Cols = LDA_Ridge_data.columns

In [130]:
bigData = df.sample(frac = .2).reset_index(drop = True)
y = bigData['target']
x = normalize(bigData[svm1Cols])

In [131]:
svmCLF.fit(x, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [132]:
svmClf_predicted = svmCLF.predict(x)

In [133]:
sc = svmCLF.score(x,y)
sc

0.9012

In [134]:
from sklearn.metrics import confusion_matrix
x = confusion_matrix(y, svmClf_predicted)
print(x)
(z, o) = analyze_Confusion(x)
scores.append(sc)
ones.append(o)
zeros.append(z)

[[36048     0]
 [ 3952     0]]
Model predicted Zeros 100.0% correctly.
Model predicted Ones 0.0% correctly.


**Using only Ridge, LDA, and Correlation w/ threshold of +-.025 for Logistic AFTER NORMALIZING (Model 8)**

*I used the SVM Classifier for this model.*

*I used the same data that was fed into the second Logistic Regression model into this Classifier, however the results showed to be not effective at all. The mdodel was prediting all 0's and not a single 1, and the reason the score looks good is because the majority of the target values were 0's. This is why we have to look at more of the metrics such as the confusion matrix and analyze it.*

In [136]:
svmCLF = SVC(gamma='auto') #BY NOT NORMALIZING, THE SET WAS AMAZING

In [137]:
bigData = df.sample(frac = .2).reset_index(drop = True)
y = bigData['target']
x = normalize(bigData[m2Columns])

In [139]:
svmCLF.fit(x, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [140]:
svmClf_predicted = svmCLF.predict(x)

In [141]:
sc = svmCLF.score(x,y)

In [142]:
from sklearn.metrics import confusion_matrix
x = confusion_matrix(y, svmClf_predicted)
print(x)
(z, o) = analyze_Confusion(x)
scores.append(sc)
ones.append(o)
zeros.append(z)

[[35976     0]
 [ 4024     0]]
Model predicted Zeros 100.0% correctly.
Model predicted Ones 0.0% correctly.


**SVM Using Correlation and K Best Feature Selector AFTER NORMALIZING (Model 9)**

*I used the SVM Classifier for this model.*

*I used the same dataset as I did for the third Logistic Regression model, as I wanted to see how the SVM model performed on the data with similar features. It did not perform well as seen with the previous SVM models, that the model is predicting all 0's regardless of the x-values, and is not even predicting a one.*

In [144]:
model9 = SVC(gamma='auto')

In [145]:
bigData = df.sample(frac = .3).reset_index(drop = True)
y = bigData['target']
x = normalize(bigData[m3Columns])

In [146]:
model9.fit(x, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [147]:
model9_predicted = model9.predict(x)

In [148]:
sc = model9.score(x,y)
sc

0.8998333333333334

In [149]:
from sklearn.metrics import confusion_matrix
x = confusion_matrix(y, model9_predicted)
print(x)
(z, o) = analyze_Confusion(x)
scores.append(sc)
ones.append(o)
zeros.append(z)

[[53990     0]
 [ 6010     0]]
Model predicted Zeros 100.0% correctly.
Model predicted Ones 0.0% correctly.


**Using only Ridge, LDA, and Correlation w/ threshold of +-.025 for Logistic WITHOUT NORMALIZING (Model 10)**

*I used the SVM Classifier for this model.*

*I used the same non-normalized data of the features being extracted from the technique of model 4, and ran this model with those features. I wanted to try running the SVM on non-normalized values for the same reason as I tried it with the regression models in the fact that by normalizing the data, the model would not be able to recognize the outlier values as all of the x-values would be too close to one another to distinguish the outliers.*

*This model at first seems to be the best performing as it has a score of 100%, and predicted all of the 1's and zero's correctly of the train set. However, it is learly visible that the model is overfitting the data as it should never be 100% on a training set, or else it means your model is too unique and is only for this data in specific, but will be inaccurate in predicting other data.*

In [150]:
model10 = SVC(gamma='auto')

In [151]:
bigData = df.sample(frac = .2).reset_index(drop = True)
y = bigData['target']
x = bigData[m4Columns]

In [152]:
model10.fit(x, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [153]:
model10_predicted = model10.predict(x)

In [154]:
sc = model10.score(x,y)
sc

1.0

In [155]:
from sklearn.metrics import confusion_matrix
x = confusion_matrix(y, model10_predicted)
print(x)
(z, o) = analyze_Confusion(x)
scores.append(sc)
ones.append(o)
zeros.append(z)

[[36048     0]
 [    0  3952]]
Model predicted Zeros 100.0% correctly.
Model predicted Ones 100.0% correctly.


# Analyzing the Scores of the Model

*The Table below shows the score of each model, and how accurate they predicted correct 1's, and correct 0's.*

In [171]:
df = pd.DataFrame({'Model Scores' : scores, 
                  'Percentage of Correct 1s (%)' : ones,
                  'Percentage of Correct 0s (%)' : zeros})
df.index = ['Model 1','Model 2','Model 3','Model 4','Model 5','Model 6','Model 7','Model 8','Model 9','Model 10']
df

Model Scores  Percentage of Correct 1s (%)  \
Model 1       0.899675                      0.243805   
Model 2       0.899675                      0.243805   
Model 3       0.904130                      7.453478   
Model 4       0.905080                     11.115534   
Model 5       0.904470                     10.204996   
Model 6       0.906095                     13.105782   
Model 7       0.901200                      0.000000   
Model 8       0.899400                      0.000000   
Model 9       0.899833                      0.000000   
Model 10      1.000000                    100.000000   

          Percentage of Correct 0s (%)  
Model 1                      99.991106  
Model 2                      99.991106  
Model 3                      99.680937  
Model 4                      99.377439  
Model 5                      99.411346  
Model 6                      99.267935  
Model 7                     100.000000  
Model 8                     100.000000  
Model 9                     100.000000  
Model 10                    100.000000

# Predicting the Test Set & ML Challenges

*I did not want to use model 10 as this model clearly seemed to overfit, and I did not want to use any of the SVM models (7,8,9) as they never were predicting ones at all. In addition, the computational cost of using the SVM models is extremely more than the cost of using Logistic Regression, so SVM would be a bad approach to use to predict the test values in my opinion. This left me with 6 models to choose from (1-6), however, I elimenated the first three models to choose from as they relied on normalized data to be pased through to the model, but as I stated before, I felt that the normalized data did not help the model in predicting ones effectively in comparasion with the other models. Then, after looking at the scores and the confusion matrices, I was down to picking between model 4 and 6. Model 4 used Ridge regression and an LDA in order to extract features and simplify the data, while model 6 used K Best Features and removed low correlations to extract features. I however, felt uncomfortable using a model that removed features through correlation because all of the features had a correlation of plus or minus of .1 from 0, meaning that the correlation was little to none in relation to the target, so by removing a point with a correlation of .02 in comparasion to .03 would make little to no difference in my opinion. This is what led me to choose model 4 over model 6 even though model 6 predicts the percentage of ones 2% more correctly than model 4, but I felt that the features were picked with more reasoning in model 4, and could potentially outperform 6 as model 6 could have just gotten lucky. This is generally the bias-variance tradeoff that I was trying to explain, as I feel like model 4 has a more genaralized view than model 6, and can predict better on actual sets it hasn't seen before. Even though model 10 predicted 100%, it is too simple and will not genaralize on data it hasn't seen before which is why it is not a good model as well. Initially another challenge I had was that when I ran all of my models, I thought they were all great and I didn't know what to choose from, but by looking at their accuracy and confusion matrix, I got to see thie true positives and true negatives properly. Another challenge was because the SVM's take too much time to run when big data wis given to them, I had to find a way to randomlly sample the data and train them with a sample of the large data. The computational time was part of the reason the SVM models seemed unappealing. *

*Below is my model 4, which I believe is my best model, predicting on the test set.*

**Using only Ridge and LDA for Logistic Regression**

In [156]:
x_test = pd.read_csv("test.csv")
y_test = pd.read_csv("test_target.csv")

In [157]:
y_test = y_test['target']

In [158]:
x_test = x_test.drop(columns = 'ID_code')
test_drop = x_test[m4Columns]
#test_drop.append('var_17')

In [159]:
predicted = model4.predict(test_drop)

In [160]:
accuracy_score(y_test,predicted)

0.986885

In [173]:
x = confusion_matrix(y_test, predicted)
print(x)

[[197377   2623]
 [     0      0]]
