## CS559: Homework #1-1

This is a part of Assignment #1 and this assignment is due on **9/16/2020 by 11:59 PM**. You are going to submit the assignment both in format of *ipynb* and *html*. The assignment should be own work and must not be shared between classmates. Try to avoid using built-in functions. 

This assignment is about linear algebra and is more focusing on implementing functions. 

In [78]:
#Avaneesh Kolluri
#I pledge my honor that I have abided by the Stevens Honor System.

In [47]:
import math #ASK IF ITS OK TO IMPORT LIBRARIES LIKE THIS
import numpy as np

### Problem 1
- Write a function `dot_product` to calculate the dot product of two 1 by n arrays. 
```
a = array([1, 2, 3, 4])
b = array([2, 3, 4, 5])
dot_product(a,b) = 40
```

In [41]:
### Code Starts Here
def dot_product(a,b):
    sum = 0
    if(len(a) != len(b)):
        return #some error that its not going to work
    for i in range(len(a)):
        sum += a[i]*b[i]
    return sum

- Test your code after generating two random 1 by 10 arrays. 

In [44]:
### Test Starts Here
a = np.random.randint(1,15,10)
b = np.random.randint(1,15,10)
print("The dot product of " + str(a) + " and " + str(b) + " is: " + str(dot_product(a,b)))
np.dot(a,b) == dot_product(a,b)

The dot product of [ 8  5 10  9 14  3  7 11  1  6] and [ 5  4  8  7 12 12  5  6  1 13] is: 587


True

- Consider three vectors ${\bf x}_1=(1,3), {\bf x}_2=(-1,5)$, and ${\bf x}_3=(0,7)$. 

    - Find the distance of each point from the origin.

    - Find the center of three points. 

    - Rotate the coordinates by 35 degress in counter clockwise. 

    - Magnify the area by 4 times. 

In [48]:
### Code Starts Here
def distance(vector, from_point):
    x = vector[0]
    y = vector[1]
    x1 = from_point[0]
    y1 = from_point[1]
    return sqrt((x-x1)**2 + (y-y1)**2)
    
def midpoint(a,b):
    x = (a[0]+b[0])/2
    y = (a[1]+b[1])/2
    return (x,y)
    
def center(x,y,z):
    a = (x[0]+y[0]+z[0])/3
    b = (x[1]+y[1]+z[1])/3
    return (a,b)

def rotate(vector):
    x = vector[0]
    y = vector[1]
    a = (x*math.cos(math.radians(35))) - (y * math.sin(math.radians(35)))
    b = (y*math.cos(math.radians(35))) + (x * math.sin(math.radians(35)))
    return (a,b)
    
def triangleAreaMagnify(a,b,c):
    s1 = distance(a,b)
    s2 = distance(a,c)
    s3 = distance(b,c)
    perimeter = s1+s2+s3
    temp = perimeter/2
    area = sqrt(temp*(temp-s1)*(temp-s3)*(temp-s2))
    return 4*area

In [60]:
#DISPLAY THE ANSWERS FOR ALL OF THEM!
x1 = (1,3)
x2 = (-1,5)
x3 = (0,7)

In [63]:
print("The distance for x1 from the origin is " + str(distance(x1,(0,0))))
print("The distance for x2 from the origin is " + str(distance(x2,(0,0))))
print("The distance for x3 from the origin is " + str(distance(x3,(0,0))))

The distance for x1 from the origin is 3.1622776601683795
The distance for x2 from the origin is 5.0990195135927845
The distance for x3 from the origin is 7.0


In [64]:
print("The center of 3 points are: " + str(center(x1,x2,x3)))

The center of 3 points are: (0.0, 5.0)


In [68]:
print("The rotation of vector x1 is: " + str(rotate(x1)))
print("The rotation of vector x2 is: " + str(rotate(x2)))
print("The rotation of vector x3 is: " + str(rotate(x3)))

The rotation of vector x1 is: (-0.9015772647641463, 3.0310325692180213)
The rotation of vector x2 is: (-3.687034226044222, 3.5221837850939126)
The rotation of vector x3 is: (-4.015035054457322, 5.7340643100229425)


In [70]:
print("The magnified area 4 times is: " + str(triangleAreaMagnify(x1,x2,x3)))

The magnified area 4 times is: 12.000000000000007


### Problem 2
- Write a function `mat_product` to calculate the matrix product of two n by n arrays. For example:


$A = \begin{bmatrix} 1 & 3 & 0 \\ 2 & 0 & 2 \\ 1 & 1 & 4 \end{bmatrix}$ and $A\cdot A=\begin{bmatrix} 7 & 3 & 6 \\ 4 & 8 & 8 \\ 7 & 8 & 18 \end{bmatrix}$

In [71]:
### Code Starts Here
def mat_product(a,b):
    final = []
    for i in range(len(a)):
        temp = []
        for j in range(len(a)):
            temp += [0]
        final.append(temp)
    
    for i in range(len(a)): 
        #print(final)
        for j in range(len(b)): 
            for k in range(len(b)):
                #print("i is: "+str(i)+'; j is: '+str(j)+" k is: "+ str(k))
                final[i][j] += a[i][k] * b[k][j]
                #print(final[i][j])
    return final

Test your code after generating two random 4 by 4 matrices, ${\bf X}$ and ${\bf Y}$.  

In [72]:
### Test Starts Here
matrix1 = np.random.random_integers(0,20,(4,4))
matrix2 = np.random.random_integers(0,20,(4,4))
print("The product of \n" + str(matrix1) + "\n and \n" + str(matrix2) + "\n is: \n" + str(mat_product(matrix1,matrix2)))
np.matmul(matrix1,matrix2) == mat_product(matrix1,matrix2)

The product of 
[[18 19 13  1]
 [ 8 13  4 14]
 [19 15 18  6]
 [ 2 14  4 18]]
 and 
[[ 9 12  0  8]
 [15  9 13  6]
 [19  7  3 13]
 [ 2 20 14  5]]
 is: 
[[696, 498, 300, 432], [371, 521, 377, 264], [750, 609, 333, 506], [340, 538, 446, 242]]


/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  This is separate from the ipykernel package so we can avoid doing imports until


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

- Transpose ${\bf X}$ and use the `mat_product` function to find the matrice of product: $Z={\bf X}^T\cdot{\bf Y}$

In [73]:
### Code Starts Here
def transpose(a):
    tot = len(a)
    arr = []
    final = []
    for i in range(tot):
        arr += [0]
    for i in range(tot):
        final += [arr]
        
    for i in range(len(a)):
        for j in range(len(a)):
            #print(final)
            final[i][j] = a[j][i]
    return final

def answerTranspose(x,y):
    return mat_product(transpose(x),y)

In [74]:
answerTranspose(matrix1,matrix2)

[[369, 540, 452, 260],
 [369, 540, 452, 260],
 [369, 540, 452, 260],
 [369, 540, 452, 260]]

### Problem 3
- Write a function, `Det`, to find the determinant of n by n matrice, `EGval`, that finds the eigenvalue $\lambda$ and a function, `EGvec`, that finds the eigenvectors ${\bf x}$
- For the confirmation, use ${\bf A}=\begin{bmatrix} 1 & 2 \\ 2 & 4 \end{bmatrix}$.

In [75]:
### Det Code Starts Here ###
A = [[1,2],[2,4]]
det = (A[0][0]*A[1][1]) - (A[0][1]*A[1][0])
print('The determinant of matrix A: ' + str(A) + " is " + str(det) + '.')
np.linalg.det(A) == det

The determinant of matrix A: [[1, 2], [2, 4]] is 0.


True

In [76]:
### EGval Code Starts Here ###
# (1-x)*(4-x) - 4 = 0
# 4 - 5x + x^2 - 4 = 0
# x^2 - 5x = 0
# x - 5 = 0
# Eigenvalue = 5 & 0
print('The eigenvalues are lambda = 5 and lambda = 0.')
np.linalg.eig(A)[0] == [0,5]

The eigenvalues are lambda = 5 and lambda = 0.


array([ True,  True])

In [77]:
### EGvec Code Starts Here ###
# for x = 5
# [[-4 , 2] , [2 , -1]] [a,b]
# -4a + 2b = 0
# 2a - b = 0 => (1 , 2)
## for x = 0
## [[1 , 2] , [2 , 4]] [a,b]
## a + 2b = 0
## 2a + 4b = 0 => (-2 , 1)
print('The eigenvectors are (1,2) when lambda = 5, and (-2,1) when lambda = 0.')
np.linalg.eig(A)

The eigenvectors are (1,2) when lambda = 5, and (-2,1) when lambda = 0.


(array([0., 5.]), array([[-0.89442719, -0.4472136 ],
        [ 0.4472136 , -0.89442719]]))